### ISSUE TITLE
Suggestion:Change title color

### ISSUE THREAD

**Issue by HimanshuAneja3** [HimanshuAneja3/LearnGitHub#1]
I think it looks better if the main title is a bit more orange.
The styling rule could be changed like this

```css
h1 {
  color: #c37f0b;
}

a {
  color: #fee389;
}
```
